// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

/*
Package waiter is a generated protocol buffer package.

It is generated from these files:
	proto/service.proto

It has these top-level messages:
	CheckInAck
	CheckInLog
*/
package waiter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// a simple OK or ERROR status
type DinerStatus int32

const (
	DinerStatus_OK    DinerStatus = 0
	DinerStatus_ERROR DinerStatus = 1
)

var DinerStatus_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var DinerStatus_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x DinerStatus) String() string {
	return proto.EnumName(DinerStatus_name, int32(x))
}
func (DinerStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CheckInAck struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *CheckInAck) Reset()                    { *m = CheckInAck{} }
func (m *CheckInAck) String() string            { return proto.CompactTextString(m) }
func (*CheckInAck) ProtoMessage()               {}
func (*CheckInAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CheckInAck) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// a checking log contains basic information for a checkin.
type CheckInLog struct {
	Ulid    string      `protobuf:"bytes,1,opt,name=ulid" json:"ulid,omitempty"`
	Status  DinerStatus `protobuf:"varint,2,opt,name=status,enum=blaedj.waiter.DinerStatus" json:"status,omitempty"`
	Message string      `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *CheckInLog) Reset()                    { *m = CheckInLog{} }
func (m *CheckInLog) String() string            { return proto.CompactTextString(m) }
func (*CheckInLog) ProtoMessage()               {}
func (*CheckInLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CheckInLog) GetUlid() string {
	if m != nil {
		return m.Ulid
	}
	return ""
}

func (m *CheckInLog) GetStatus() DinerStatus {
	if m != nil {
		return m.Status
	}
	return DinerStatus_OK
}

func (m *CheckInLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckInAck)(nil), "blaedj.waiter.CheckInAck")
	proto.RegisterType((*CheckInLog)(nil), "blaedj.waiter.CheckInLog")
	proto.RegisterEnum("blaedj.waiter.DinerStatus", DinerStatus_name, DinerStatus_value)
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x78, 0x93, 0x72,
	0x12, 0x53, 0x53, 0xb2, 0xf4, 0xca, 0x13, 0x33, 0x4b, 0x52, 0x8b, 0x94, 0x54, 0xb8, 0xb8, 0x9c,
	0x33, 0x52, 0x93, 0xb3, 0x3d, 0xf3, 0x1c, 0x93, 0xb3, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x4b, 0x12,
	0x4b, 0x4a, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c, 0xa5, 0x3c, 0xb8, 0x2a,
	0x9f, 0xfc, 0x74, 0x21, 0x21, 0x2e, 0x96, 0xd2, 0x9c, 0xcc, 0x14, 0xb0, 0x1a, 0xce, 0x20, 0x30,
	0x5b, 0xc8, 0x08, 0xae, 0x93, 0x49, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x4a, 0x0f, 0xc5, 0x1e, 0x3d,
	0x97, 0xcc, 0xbc, 0xd4, 0xa2, 0x60, 0xb0, 0x0a, 0x98, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9,
	0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0xcc, 0x60, 0xa3, 0x60, 0x5c, 0x2d, 0x05, 0x2e, 0x6e, 0x24,
	0x0d, 0x42, 0x6c, 0x5c, 0x4c, 0xfe, 0xde, 0x02, 0x0c, 0x42, 0x9c, 0x5c, 0xac, 0xae, 0x41, 0x41,
	0xfe, 0x41, 0x02, 0x8c, 0x46, 0x9e, 0x5c, 0x6c, 0xe1, 0x60, 0x93, 0x85, 0xec, 0xb9, 0xd8, 0xa1,
	0x6e, 0x13, 0x92, 0x44, 0xb3, 0x14, 0xe1, 0x66, 0x29, 0x1c, 0x52, 0x8e, 0xc9, 0xd9, 0x4e, 0x1c,
	0x51, 0x6c, 0x10, 0xc1, 0x24, 0x36, 0x70, 0x10, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6b,
	0x17, 0xd3, 0x9d, 0x39, 0x01, 0x00, 0x00,
}
